// This file is automatically generated. Do not modify it manually.
// To change the configuration, please use the Firebase console.
export const firebaseConfig = {
  apiKey: "AIzaSyAUv4znpKXrroNaVPGj0rzPgdVcRwQuUhQ",
  authDomain: "campuscheck-copia-640387-b1383.firebaseapp.com",
  projectId: "campuscheck-copia-640387-b1383",
  storageBucket: "campuscheck-copia-640387-b1383.appspot.com",
  messagingSenderId: "225670492561",
  appId: "1:225670492561:web:59c26c319508133916ea30"
};
